### ISSUE TITLE
How to use after install

### ISSUE THREAD

**Issue by rt3norio** [StartBootstrap/startbootstrap-sb-admin-2#224]
Hello!

after using `npm i startbootstrap-sb-admin-2` to install and running `npm start` nothing happens.

the files are inside node_modules but how do i use it on my project views?

how am i supposed to use this library in my project?

**Comment by piekstra** [comment]
I'm having the same problem. The instructions aren't complete. I will post an update here once I figure it out.

**Comment by piekstra** [comment]
@rt3norio I had to do the following to get the demo working:
Starting in an empty directory,
`git clone https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git`
`npm install`
`npm start`

If for whatever reason it complains about not having gulp, run the following command:
`npm install --global gulp-cli`

Reference for the above: https://stackoverflow.com/questions/22224831/after-installation-of-gulp-no-command-gulp-found
