### ISSUE TITLE
Error js 

### ISSUE THREAD

**Issue by duongnt58** [StartBootstrap/startbootstrap-sb-admin-2#229]
Uncaught TypeError: Cannot read property 'length' of null
    at Object.acquireContext (Chart.min.js:formatted:6201)
    at t.construct (Chart.min.js:formatted:2515)
    at new t (Chart.min.js:formatted:3794)
    at chart-area-demo.js:32

**Comment by aleckrh** [comment]
In which file do you get the error? Because when I open `charts.html` I do not get any errors by console.
PD. Sorry for my English.

**Comment by zhiiker** [comment]
The same with you.
Have you solve it?

**Comment by tiesont** [comment]
@zhiiker Have you modified the demo page at all? The demo script is targeting the canvas element you see [here](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/charts.html#L350), so any changes to the markup would require updating the demo. You also want to make sure that the dependencies shown on that page are all loaded - do you have any 404 errors in the developer console?

**Comment by zhiiker** [comment]
@tiesont I have solve these problem , I hava used incorrect syntax for referencing resources.
But anew bug has been created.
The error message is `Uncaught SyntaxError: Unexpected token <`

**Comment by tiesont** [comment]
@zhiiker Probably want to open a new issue for that, but that error usually indicates that you're trying to parse JSON but received HTML instead - that's not uncommon for an AJAX requested to an endpoint that's not configured correctly.
