### ISSUE TITLE
Change primary color

### ISSUE THREAD

**Issue by RoelvanDaele** [StartBootstrap/startbootstrap-sb-admin-2#250]
Hi guys,

Is is possible to change the primary color within SB Admin 2? For instance, I want to use this color as primary color #d53820.

Thanks in advance!

Roel

**Comment by tiesont** [comment]
The same process that Bootstrap suggests (see https://getbootstrap.com/docs/4.3/getting-started/theming/#variable-defaults) would work, assuming you're using some sort of Sass compiler.

You can add something like this to the top of https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/scss/sb-admin-2.scss

```css
$primary: #d53820;
```

Assuming you don't want to edit the sb-admin-2.scss file, you could (probably should) create your own `colors.scss` file with the above line, then just make sure that you import your color file before importing `sb-admin-2`. So, your custom Sass file would look something like

```css
@import 'colors.scss';
@import 'path/to/sb-admin-2.scss';

/* the rest of your styles... */
```
