### ISSUE TITLE
new js files cause infinite reload 

### ISSUE THREAD

**Issue by jonayreyes** [StartBootstrap/startbootstrap-sb-admin-2#254]
**EDIT** the same error occurs even when editing `sb-admin-2.js`

If I:
1. start with n`pm start` (fresh install)
2. add a new file under the `js` folder, (`example.js`)
3. it gets minified, just right next to `sb-admin-2.js`
4. doesn't get injected in `sb-admin-2.js`
5. causes an infinite loop:

![2019-05-22_11:07:22_flameshot](https://user-images.githubusercontent.com/2834790/58166464-cb015b80-7c81-11e9-9676-f9f6b4fa9b85.png)

Is this even supported? to add new .js files and get them bundled an added to sb-admin-2.js, or at least, injected in all html files?

**Comment by davidtmiller** [comment]
I am going to be dropping gulp in a future update, so this wont be happening.
