### ISSUE TITLE
many errors in npm install

### ISSUE THREAD

**Issue by oussamabousselmi** [StartBootstrap/startbootstrap-sb-admin-2#278]
after executing npm install it shows this error:
npm ERR! Linux 4.4.0-142-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampp/htdocs/dashboard/startbootstrap-sb-admin-2/npm-debug.log

**Comment by bobvanluijt** [comment]
I have the same issue on Mac

**Comment by davidtmiller** [comment]
Make sure to update your npm and Node and rerun. Should be working in the most recent build

**Comment by RafaelMiquelino** [comment]
Hi,

For anyone who arrives here, I also had many errors while executing `npm install` on macOS Big Sur with the following amongst others:
```
gyp: No Xcode or CLT version detected!
```
I managed to get rid of that with the solution proposed here: https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md. 

Hope it can help someone else 😊
