### ISSUE TITLE
Sidebar Hide

### ISSUE THREAD

**Issue by GiulioMartino** [StartBootstrap/startbootstrap-sb-admin-2#285]
how can I remove the automatic hide of the sidebar when the browser resizes?

**Comment by tiesont** [comment]
I'm assuming you're referring to the responsive behavior? That's controlled by this stylesheet: https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/scss/navs/_sidebar.scss

You would need to either adjust the variables or remove / change the breakpoints to change when / if the sidebar collapses.

**Comment by Floris999** [comment]
@GiulioMartino 
Something like:

@media (min-width: *width in px here*) {
    .(class) #(ID){
        display: none;
    }

**Comment by jorgeboucas** [comment]
could some one give an addition hint ?
