### ISSUE TITLE
template does not validate on validator.w3.org

### ISSUE THREAD

**Issue by stccorp** [StartBootstrap/startbootstrap-sb-admin-2#293]
Hello,  
If I copy-paste any page from the template on validator.w3.org I get a bunch of errors.  Anyone check that the template is valid?  

Thank you

**Comment by stccorp** [comment]
Element a not allowed as child of element ul in this context.
Element hr not allowed as child of element ul in this context.
Element div not allowed as child of element ul in this context. 

amount others

**Comment by WindOfNet** [comment]
same problem.
you can add li wrap not allowed element.


```
<!-- Divider -->
class="sidebar-divider">
```

to
```
<!-- Divider -->
<li>
    <hr class="sidebar-divider">
</li>
```

**Comment by davidtmiller** [comment]
#355 will address this in the next build!
