### ISSUE TITLE
Sidebar Hide when scrolling down on iPhone

### ISSUE THREAD

**Issue by IsidroMar95** [StartBootstrap/startbootstrap-sb-admin-2#303]
On mobile version when the sidebar is open and i scroll down the sidebar get hide and i dont know why.

i've tried on Chrome, Safari and Firefox on iPhone 7 ( 375x667px) iOS 13.1.3 and the bug still there, but for example on Android Phone (424x918px) the Sidebar is fine when i scrolling down 

is this a normal behavior? how can i fix this?
![issue](https://user-images.githubusercontent.com/23019968/67914575-2c452900-fb56-11e9-8302-69c3903ff874.gif)

**Comment by sitehandy** [comment]
I just commented on the following js in the sb-admin-2.js (make sure you use sb-admin-2.js and not the sb-admin-2.min.js). By default, I use the following class in my sidebar `sidebar-toggled toggled`

`// Close any open menu accordions when the window is resized below 768px
  // $(window).resize(function() {
  //   if ($(window).width() < 768) {
  //     $('.sidebar .collapse').collapse('hide');
  //   }
    
  //   // Toggle the side navigation when window is resized below 480px
  //if ($(window).width() < 480 AND !$(".sidebar").hasClass("toggled")) {
  //     $("body").addClass("sidebar-toggled");
  //     $(".sidebar").addClass("toggled");
  //     $('.sidebar .collapse').collapse('hide');
  //   }
  // });`

**Comment by jerontx** [comment]
OMG thank you so much for this fix!!! It worked!
