### ISSUE TITLE
Active class in menu items in sidebar not found.

### ISSUE THREAD

**Issue by NLeone** [StartBootstrap/startbootstrap-sb-admin-2#307]
Good afternoon dear, I comment that I am using the template next to the Yii2 framework, it works wonders, I have associated all the assets you need, the drawback is that when I click on a link it does not fit as an asset, I have looked for similar problems and I have reviewed the sample code in the template but I do not see what I can be doing wrong, I enclose a screenshot of a list of records as seen, and the code I have on the sidebar to see if anyone can advise me something. Thank you very much in advance! Regards!

![Captura de pantalla de 2019-11-11 14-22-03](https://user-images.githubusercontent.com/964781/68607112-a9de3280-048e-11ea-8b36-d1ff4c0d47c5.png)

                <div class="sidebar-heading">
                    Gremios
                </div>
                
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseSindicatos" aria-expanded="true" aria-controls="collapseSindicatos">
                        <i class="fas fa-building"></i>
                        <span>Sindicatos</span>
                    </a>
                    <div id="collapseSindicatos" class="collapse" aria-labelledby="headingSindicatos" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Operaciones:</h6>
                            
                            <?= Html::a('Listar', ['sindicato/index'], ['class' => 'collapse-item']) ?>
                            
                            <?= Html::a('Crear', ['sindicato/create'], ['class' => 'collapse-item']) ?>
                        
                        </div>
                    </div>
                </li>

**Comment by NLeone** [comment]
Anyone who can help me? this topic is driving me crazy, it sure is something that I am not programming well, I don't know if the urls will be, but I don't know where to see at what moment the active class is injected to the navigation items, maybe if I saw that I could try to modify a little code.

Please someone who has been through the same. Cheers !

**Comment by pixelbart** [comment]
The classes must be attached to the following ones:

`.nav-link.active` > `.collapse-item.active`

**Comment by NLeone** [comment]
> The classes must be attached to the following ones:
> 
> `.nav-link.active` > `.collapse-item.active`

Dear, thank you very much for your response, I appreciate it very much!
But sorry I still do not understand, I have in my php in the view of my framework everything working fine except what I mentioned, and what I did was to replicate that I saw in the examples, then my link is like this <? = Html :: a ('Altitudes', ['altitude / index'], ['class' => 'collapse-item'])?>, everything else works fine except that the link is active, where it says to add what it mentions at its point.

Again I thank you for your time, very good contribution! I await your response when I can.

**Comment by pixelbart** [comment]
The problem is that there is not much to do with your information. You have to know what the parameters are called when a certain page is called.

Then you can make an if-then query and add a class.

For example:

```php
$options = [ 'class' => 'collapse-item' ];

if ( 'my-param' === $_GET['url-param'] ) {
    Html::addCssClass( $options, [ 'active' ] );
}

Html::a( 'Crear', [ 'sindicato/create' ], $options )
```

**Comment by NLeone** [comment]
> The problem is that there is not much to do with your information. You have to know what the parameters are called when a certain page is called.
> 
> Then you can make an if-then query and add a class.
> 
> For example:
> 
> ```
> $options = [ 'class' => 'collapse-item' ];
> 
> if ( 'my-param' === $_GET['url-param'] ) {
>     Html::addCssClass( $options, [ 'active' ] );
> }
> 
> Html::a( 'Crear', [ 'sindicato/create' ], $options )
> ```

Hello! I do not know why the notification came to me now about your answer, I have been in other projects and I have not advanced with this topic since it was not about front end my work in these times. I consult you, I am still unable to activate the menu items, what type of information can I provide other than the one mentioned above, so that you can help me in this regard. I love this template but this is a defect that I cannot solve and it must surely be something simple for others but not for me. I have used the AdminLTE template and I have not had this problem, but I like it much more, can you help me please;)

**Comment by pixelbart** [comment]
I have named the groups at my place and so I access the Childs. But I also work with PHP, maybe it is easier with this.

I always have a main menu item and corresponding childs. If a child is active, the parent is also active. You only have to name the parent, so the child knows where it belongs.

I hope you understand me a little bit.

**Comment by NLeone** [comment]
> I have named the groups at my place and so I access the Childs. But I also work with PHP, maybe it is easier with this.
> 
> I always have a main menu item and corresponding childs. If a child is active, the parent is also active. You only have to name the parent, so the child knows where it belongs.
> 
> I hope you understand me a little bit.

Hello dear, thank you very much for answering, I understand about the child classes, but I honestly need a specific example in php, it does not matter that I then use my framework, how would you program "nav-item active" and "collapse-item active" , I can get the url to act through a function of my framework and thus add a short conditional, but honestly it seems that I am inside a jar and I need a little help with this, in html I don't know how magic happens, where is the javascript code that does this, I do not think that in html it is only css who decides when to activate and when not, that's what I mean, in other templates when using them with php I did not have to make any modification to take the current url, I understand that it must It will be a job they do in javascript, but in fact I have never asked myself until now.

Thank you very much for your reply!

**Comment by NLeone** [comment]
Basically what I need to know is how it currently does in the demo, because when I go to any example page in the demo the nav-item and the collapse-item are automatically activated, exactly the same behavior is what I need. I think that if I do it with php in each item, I will definitely have too many conditionals in my case I have about 30 menu items ...

I need something more productive and really the same behavior as the demo. I would appreciate the help, greetings!

**Comment by davidtmiller** [comment]
Yes at the moment there are two classes that need to be active for the active states to function properly. The dropdowns in the side navigation need to be active to show as open, and the item itself in the dropdown needs to be active to remain active. It's not ideal, and in a future build we may work something in that uses a bit of JS to keep the dropdowns open and items active simultaneously with only a single class being used.
