### ISSUE TITLE
[feature] Provide sidebar has sub menu

### ISSUE THREAD

**Issue by iyilm4z** [StartBootstrap/startbootstrap-sb-admin-2#316]
I want to implement an advanced angular implementation of this nice looking theme, [here](https://github.com/iyilm4z/ngx-sb-admin) is my repo. But current sidebar implementation is really so bad, that's why i can't implement recursive tree menu because there is no hierarchy, no pattern with the menu structure. There is also [another issue](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/issues/246) related to this topic. Please make sidebar better.

**Comment by davidtmiller** [comment]
The current sidebar is going to get simplified quite a bit in an upcoming build, closing this for now since it will no longer be relevant as we develop the new version.
