### ISSUE TITLE
[feature] Provide theme has right sidebar

### ISSUE THREAD

**Issue by iyilm4z** [StartBootstrap/startbootstrap-sb-admin-2#317]
In order to configure theme make us having right sidebar/control sidebar. 
Also make it having an option to show/hide it like modal(with overlays), this option can make us to use this right sidebar for showing detailed infos like showing details of an invoice as quick view in an e-commerce app like in this example. [Source](https://uxdesign.cc/design-better-data-tables-4ecc99d23356).

![1_Tt2x8SRugOlJQNsMdidF_g](https://user-images.githubusercontent.com/9105939/71611729-93aa4400-2bac-11ea-90ff-35d11260148c.gif)

**Comment by davidtmiller** [comment]
An off canvas sidebar is something that users can certainly build into the theme, but it is more a of specific use case that is past the scope of what we're trying to include with this specific theme.
