### ISSUE TITLE
[feature] Provide theme has horizontal menu a.k.a top menu

### ISSUE THREAD

**Issue by iyilm4z** [StartBootstrap/startbootstrap-sb-admin-2#318]
In some apps, it's way better to use horizontal menu in order to have more screen area. So make us having horizontal menu a.k.a top menu.

**Comment by davidtmiller** [comment]
A secondary top menu is something that users could add themselves, but for the purposes of this theme we are going to stick to the single sidebar and single top navigation for the time being.
