### ISSUE TITLE
Datatables doesn't use Bootstrap layout in ajax populated datatables.

### ISSUE THREAD

**Issue by mohitYogi** [StartBootstrap/startbootstrap-sb-admin-2#330]
In normal data-tables i.e. when data is already available in table element in HTML the bootstrap layout works fine, like wrapping elements with "row", "col-md-6" etc works fine.
[SEE THIS](http://prntscr.com/rhmbyc)

When I try to populate the datatable using Ajax, bootstrap layouts are not used & things get mis-aligned.
[SEE THIS](http://prntscr.com/rhmayo)

Please help with this issue.

**Comment by davidtmiller** [comment]
Make sure the dataTables BS4 plugin CSS is loading properly and this should get resolved. Hopefully this helps!
