### ISSUE TITLE
Navbar always open on mobile devices

### ISSUE THREAD

**Issue by patrick7** [StartBootstrap/startbootstrap-sb-admin-2#335]
To show all navigation items which belong to one category, I use the "show" class for the active menu.
Now, on mobile devices, the menu always opens. Is there a possibility to change the behaviour?

**Comment by moustafa-mneimneih** [comment]
I'm having this same issue as well. 

On browser, when the window is reduced, it automatically collapses the sidenav bar to the small navbar. When the window is made smaller, mobile size, it automatically hides the side navbar. 

Upon refreshing the page whilst on the mobile view, it pops open the side navbar again. 

Can this behaviour be changed, as per patrick7 request, to have the sidenavbar collapsed on mobile devices?

**Comment by thdemarty** [comment]
You can change it by adding the `.toggled` class to the sidebar. But your sidebar will be minimized also for desktop.

**Comment by patrick7** [comment]
Use

`
<script>
  | $(function () {
  | var $activeNavbar = $('.sidebar .collapse.show-initial');
  | if ($(window).width() >= 768) $activeNavbar.addClass('show');
  | $activeNavbar.removeClass('show-initial');
  |  
  | $(window).resize(function () {
  | if ($(window).width() >= 768) $('.sidebar .nav-item.active .collapse').collapse('show');
  | });
  | });
  | </script>
`

and add show-initial to the menu which should be opened by default.

**Comment by davidtmiller** [comment]
The toggled class is handled via media queries at the moment I believe. We'll be moving to how we handle the menu in SB Admin soon, so I'll be closing this for now since it will no longer be relevant in the upcoming build.

**Comment by edytjung** [comment]
`
<script>
        $(document).ready(function() {
            function isMobileDevice() {
                return /Mobi|Android/i.test(navigator.userAgent);
            }

            if (isMobileDevice()) {
                // Execute the script for mobile devices
                $('#accordionSidebar').hide();
                // Add more script here
            }

        });
    </script>
`

just put that script, online at mobile view sidebar is hidden.
