### ISSUE TITLE
is there a dark mode css option?

### ISSUE THREAD

**Issue by ppazos** [StartBootstrap/startbootstrap-sb-admin-2#342]

**Comment by danielmoeck** [comment]
Could someone respond to this? I've got the same question :-) Thanks.

**Comment by tiesont** [comment]
No, this template does not have a "dark mode".

**Comment by davidtmiller** [comment]
At the moment this theme doesn't have a dark mode available, but it's something that I may be open to developing. Another possibility is that a dark mode feature might be something we work into our SB Admin Pro theme.

**Comment by lukasmedia** [comment]
Please add this option :+1:

**Comment by TimothyBramlett** [comment]
@davidtmiller @tiesont SB Admin Pro Customer here. Any update on this?

**Comment by TimothyBramlett** [comment]
Also you added this tag duplicate but didn't link to the duplicate? Tricky, very tricky. 🤔
