### ISSUE TITLE
Display status indicator to current user

### ISSUE THREAD

**Issue by thdemarty** [StartBootstrap/startbootstrap-sb-admin-2#345]
I got an issue, 

I wanted to know how is it possible to display a status indicator as is it displayed for the message center of the dashboard for each user, to the current user connected (where it is written Valerie Luna).
Do you have any idea ?

**Comment by davidtmiller** [comment]
The status indicators used on the other menu items are set using some custom CSS using absolute positioning and some top and left offsets. Make sure the parent is a relative position before doing something similar in that item!
