### ISSUE TITLE
Tables Search Box Shadow

### ISSUE THREAD

**Issue by vnportnoy** [StartBootstrap/startbootstrap-sb-admin-2#347]
When focusing on the search box of the tables there is a glitch on the shadow effect.
On desktop it shows just for the bottom and left borders.
But on mobile it works fine and shows the effect on all four borders.

**Comment by davidtmiller** [comment]
I've run into this with the DataTables plugin before. It has something to do with the overflow property of the parent element to the input along with the box shadow being used in place of the outline property for the focus states. I will try to find a fix for this in an upcoming update!
