### ISSUE TITLE
jQuery: moderate severity vulnerability

### ISSUE THREAD

**Issue by maoaiz** [StartBootstrap/startbootstrap-sb-admin-2#350]
Hi everyone, npm shows a moderate severity vulnerability fixed in the recent update of jquery

![Screenshot_20200525_171834](https://user-images.githubusercontent.com/1550196/82845913-0db8cd80-9eac-11ea-964e-2c529bdac546.png)

Can you please update the dependency?

**Comment by xsuchy09** [comment]
There is a "bot" pull request for this issue - https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/pull/337

**Comment by davidtmiller** [comment]
Updated!
