### ISSUE TITLE
generate report button hidden on mobile

### ISSUE THREAD

**Issue by srggrs** [StartBootstrap/startbootstrap-sb-admin-2#351]
When index is viewed on mobile, the "generate report" button is hidden.
![image](https://user-images.githubusercontent.com/34258464/83483110-40cf1280-a4e5-11ea-8c8a-b52d8234a21a.png)

Normally is like this:
![image](https://user-images.githubusercontent.com/34258464/83483079-2eed6f80-a4e5-11ea-98e2-7edac58af096.png)

**Comment by davidtmiller** [comment]
This is by design. You can bring it back if you want to by removing the following utility classes attached to the button: `d-none` and `d-sm-inline-block`

**Comment by srggrs** [comment]
thx!
