### ISSUE TITLE
Side Navigation Toggle

### ISSUE THREAD

**Issue by wandyyd** [StartBootstrap/startbootstrap-sb-admin-2#373]
Hi there,

Thanks for the awesome templates!

At the moment, I'm using it to learn for **Laravel + vueJS**.
I found for Side Navigation toggle event on [**/js/sb-admin-2.js**](https://github.com/StartBootstrap/startbootstrap-sb-admin-2/blob/master/js/sb-admin-2.js) having an issue, which the toggle event is not attached to the button, since on vueJS, (I think) the component/element are loaded/rendered kind of asynchronously (sorry for the term, I'm still newbie on this front-end world).

I'm not pretty sure, either,
- On how I load things around - since I'm using Laravel Mix Webpack to manage javascript dependencies, or
- That's the way vueJS works (as I mentioned before, I'm still newbie on front-end world), which load the component/element a bit late after the elements being loaded/rendered

So to overcome that particular issue, I did some adjustment directly on that particular file,
1. Adjustment for the Side Navigation toggle, and
2. Side Navigation scroll prevention (not pretty sure for this one, but it seems it will cause the same issue)

So, regardless the component/element being loaded/rendered a bit late / asynchronously, that particular component/element will still having its event, in this case, toggle event.

<details>
<summary>Code snippet - before</summary>
<pre>
// Toggle the side navigation
  $("#sidebarToggle, #sidebarToggleTop").on('click', function(e) {
    $("body").toggleClass("sidebar-toggled");
    $(".sidebar").toggleClass("toggled");
    if ($(".sidebar").hasClass("toggled")) {
      $('.sidebar .collapse').collapse('hide');
    };
  });
...
  // Prevent the content wrapper from scrolling when the fixed side navigation hovered over
  $('body.fixed-nav .sidebar').on('mousewheel DOMMouseScroll wheel', function(e) {
    if ($(window).width() > 768) {
      var e0 = e.originalEvent,
        delta = e0.wheelDelta || -e0.detail;
      this.scrollTop += (delta < 0 ? 1 : -1) * 30;
      e.preventDefault();
    }
  });
</pre>
</details>

<details>
<summary>Code snippet - after</summary>

<pre>
  // Toggle the side navigation
  $(document).on('click', '#sidebarToggle, #sidebarToggleTop', function(e) {
    $("body").toggleClass("sidebar-toggled");
    $(".sidebar").toggleClass("toggled");
    if ($(".sidebar").hasClass("toggled")) {
      $('.sidebar .collapse').collapse('hide');
    };
  });
...
  // Prevent the content wrapper from scrolling when the fixed side navigation hovered over
  $(document).on('mousewheel DOMMouseScroll wheel', 'body.fixed-nav .sidebar', function(e) {
    if ($(window).width() > 768) {
      var e0 = e.originalEvent,
        delta = e0.wheelDelta || -e0.detail;
      this.scrollTop += (delta < 0 ? 1 : -1) * 30;
      e.preventDefault();
    }
  });
</pre>
</details>

I'm hoping someone can update the code perhaps(?) (or PR?)
Sorry, I'm a newbie too on this github world lol! :laughing:
Or maybe, someone can teach me how to do it easily? (I'm checking the guide and its kinda complicated :sweat_smile:)
I'm really happy if so.

Thanks - have a wonderful day! :smile:

**Comment by hfl** [comment]
Good, I have same problem when I use sb-admin-2 as Rails 6 template.
I have fix that in my template.
thank you.
