### ISSUE TITLE
Compatibility with Font Awesome Pro

### ISSUE THREAD

**Issue by sean8300** [StartBootstrap/startbootstrap-sb-admin-2#391]
If I import FA pro the arrows on the left menu are replaced with the text  "F105" (when pointing left/collapsed) and "F107" (when pointing down/expanded).  If I bring in the free version of FA and remove the pro I get my arrows back but then I lose the pro icons.

Is there a quick way around this that I'm missing?

**Comment by tiesont** [comment]
Are you using the same version of Font Awesome? The classes used in FA4 are not the same as FA5. The pro version also has a different font family than the free version in FA5, so you can't just swap the font files - you have to replace the CSS file as well.

**Comment by tiesont** [comment]
Font Awesome Pro uses a different font family, so if you want to use that, you'll need to edit either the Sass file or the compiled CSS, depending on which you're using. 

For the Sass version, the Font Awesome bits for the sidebar start here: https://github.com/StartBootstrap/startbootstrap-sb-admin-2/blob/master/scss/navs/_sidebar.scss#L104

For the CSS version, you'd start here: https://github.com/StartBootstrap/startbootstrap-sb-admin-2/blob/master/css/sb-admin-2.css#L10096

I imagine a find and replace would work for either.

**Comment by sean8300** [comment]
Looks like that did it.  Thank you so much!
